config/routes.rb
IMDbWidget::Application.routes.draw do
  get "home/index"
  match '/find', to: 'home#find'

  root :to => 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
  
  def find
    public_url = params[:address].empty? ? "http://www.imdb.com/user/ur27065058/ratings" : params[:address]   
    doc = Nokogiri::HTML(open(public_url))
    @user_href = "http://www.imb.com" << doc.css("div#main").css("div.article").css("h3").css("a").first["href"]
    @user_name = doc.css("div#main").css("div.article").css("h3").css("a").first.text
    ids = find_ids_and_features(doc) # ids = [[title_id1, director_url1], [title_id2, director_url2], ...]
    @movies = {}
    i = 0
    ids.each do |tt|
      movie = Imdb::Movie.new(tt[0])
      star1_url = "http://www.imdb.com/name/"<< movie.cast_member_ids[0]
      star2_url = "http://www.imdb.com/name/"<< movie.cast_member_ids[1]
      star3_url = "http://www.imdb.com/name/"<< movie.cast_member_ids[2]
      movie_url = "http://www.imdb.com/title/tt" << tt[0]
      poster = movie.poster.nil? ? "/assets/film.png" : movie.poster
      @movies[i] = {:id => movie.id, :url => movie_url, :title => movie.title, :poster => poster, :plot => movie.plot,
                    :rating => movie.rating, :year => movie.year, :length => movie.length, :director => movie.director[0],
                    :director_url => tt[1], :star1 => movie.cast_members[0], :star2 => movie.cast_members[1],
                    :star3 => movie.cast_members[2], :star1_url => star1_url, :star2_url => star2_url, :star3_url => star3_url}
      i += 1
    end
  end
  
  def find_ids_and_features(doc)
    ids = []
    list_items = doc.css("div .list_item").each do |item|
      check_if_episode = item.css("div.info").css("div.episode")
      if check_if_episode.empty? # movie
        parse_title_id = item.css("div.image").css("a").first
        title_id = parse_title_id["href"].split("tt")[1].split("/")[0]
        parse_director_url = item.css("div.info").css("div.secondary").first
        if parse_director_url.text.include? "Director" # some items don't show director info on IMDb rating list, pass them.
          director_url = "http://www.imdb.com" << parse_director_url.css("a").first["href"]
          parse_stars_urls = item.css("div.info").css("div.secondary")[1]
          if parse_stars_urls.text.include? "Star" # some items don't show star info, so pass them, too.
            ids << [title_id, director_url]
          end
        end
        return ids if ids.size == 3 # just fetching first five movies for widget
      end
    end
    ids
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/find.html.erb
<div class="table-responsive">
  <div class="widget1_alignment">
    <div class="widget1">
      <strong>
        <p class="text-center"><%= link_to @user_name, @user_href, :target => "_blank" %>'s last ratings</p>
      </strong>
  	  <table class="table table-condensed">
  	    <% @movies.each do |index, movie| %>
  	  	  <tr class="last_tr">
  	  	    <td rowspan="4" width="70" class="first_td">
  	  	      <%= link_to image_tag(movie[:poster], size: "80x105"), movie[:url], :target => "_blank" %>
  	  	      &nbsp;
  	  	      <div class="star-box giga-star">
  	  	        <div class="titlePageSprite star-box-giga-star">&nbsp;<%= movie[:rating] %></div>
  	  	      </div>
  	  	    </td>
  	  	    <td>
  	  	      <%= link_to movie[:title], movie[:url], :target => "_blank" %>
  	  	      <p class="text-muted" style="display: inline;">(<%= movie[:year] %>)</p>
  	  	      <p class="text-muted" style="display: inline;">(<%= movie[:length] %> min)</p>
  	  	    </td>
  	  	  </tr>
  	  	  <tr><td><small>Director: <%= link_to movie[:director], movie[:director_url], :target => "_blank" %></small></td></tr>
  	  	  <tr>
  	  	    <td>
  	  	      <small>Stars: <%= link_to movie[:star1], movie[:star1_url], :target => "_blank" %>,
  	  	                    <%= link_to movie[:star2], movie[:star2_url], :target => "_blank" %>,
  	  	                    <%= link_to movie[:star3], movie[:star3_url], :target => "_blank" %>
  	  	      </small> 
  	  	    </td>
  	  	  </tr>
  	  	  <tr class="last_tr">
  	  	    <td>
  	  	      <small><em><%= movie[:plot] %></em></small>
  	  	    </td>
  	  	  </tr>
  	    <% end %>
  	  </table>
  	  <p class="text-center text-muted"><em>Developed by <%= link_to "Mshn", "http://rekursifdusunce.blogspot.com", :target => "_blank" %></em></p>
  	</div>
  </div>
</div>

app/views/home/index.html.erb
<%= form_tag(find_path, method: "get") do %>
	<div class="table-responsive">
	  <div class="index_alignment">
		<div class="row">
		  <div class="col-lg-6">
		    <div class="input-group">
		      <label class="sr-only" for="url">Public Rating URL</label>
			    <div>
			      <%= text_field_tag :ratings, nil, :placeholder => "http://www.imdb.com/user/ur27065058/ratings", :class => "form-control" %>
			    </div>
		      <span class="input-group-btn">
		      	<%= link_to 'Find!', '#', class: "btn btn-default", :onclick => "window.location.href = '/find?address='+ $('#ratings').val();" %>
		      </span>
		    </div><!-- /input-group -->
		  </div><!-- /.col-lg-6 -->
		</div><!-- /.row -->
		</div>
	  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IMDbWidget</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>